-- V1__init_schema.sql
-- Corebank-lite: khởi tạo schema cho Oracle 21c
-- Chạy bởi Flyway với user corebank_app (đã được cấp quyền CREATE TABLE/SEQUENCE/...)

-- ========== USERS ==========
CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50)  NOT NULL UNIQUE,
    password_hash   VARCHAR2(255) NOT NULL,
    full_name       VARCHAR2(150) NOT NULL,
    role            VARCHAR2(20)  DEFAULT 'CUSTOMER' NOT NULL
                        CHECK (role IN ('CUSTOMER', 'TELLER', 'ADMIN')),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ========== ACCOUNTS ==========
CREATE TABLE accounts (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number  VARCHAR2(20)  NOT NULL UNIQUE,
    user_id         NUMBER        NOT NULL REFERENCES users(id),
    balance         NUMBER(18,2)  DEFAULT 0 NOT NULL CHECK (balance >= 0),
    status          VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL
                        CHECK (status IN ('PENDING', 'ACTIVE', 'LOCKED', 'CLOSED')),
    daily_limit     NUMBER(18,2)  DEFAULT 1000000000 NOT NULL,
    per_txn_limit   NUMBER(18,2)  DEFAULT 500000000 NOT NULL,
    version         NUMBER        DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_accounts_user_id ON accounts(user_id);

-- ========== TRANSACTIONS ==========
CREATE TABLE transactions (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key   VARCHAR2(64)  NOT NULL UNIQUE,
    from_account_id   NUMBER        NOT NULL REFERENCES accounts(id),
    to_account_id     NUMBER        NOT NULL REFERENCES accounts(id),
    amount            NUMBER(18,2)  NOT NULL CHECK (amount > 0),
    status            VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL
                          CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'REVERSED')),
    failure_reason    VARCHAR2(255),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at      TIMESTAMP,
    CONSTRAINT chk_diff_accounts CHECK (from_account_id <> to_account_id)
);
CREATE INDEX idx_txn_from ON transactions(from_account_id);
CREATE INDEX idx_txn_to   ON transactions(to_account_id);
CREATE INDEX idx_txn_status_created ON transactions(status, created_at);

-- ========== AUDIT LOGS ==========
CREATE TABLE audit_logs (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR2(50) NOT NULL,
    entity_id     NUMBER       NOT NULL,
    action        VARCHAR2(50) NOT NULL,
    old_value     CLOB CHECK (old_value IS JSON),
    new_value     CLOB CHECK (new_value IS JSON),
    performed_by  NUMBER REFERENCES users(id),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);

-- ========== TRANSACTION OUTBOX ==========
CREATE TABLE transaction_outbox (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  NUMBER NOT NULL REFERENCES transactions(id),
    event_type      VARCHAR2(50) NOT NULL,
    payload         CLOB NOT NULL CHECK (payload IS JSON),
    published       NUMBER(1) DEFAULT 0 NOT NULL CHECK (published IN (0,1)),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_outbox_unpub
    ON transaction_outbox(CASE WHEN published = 0 THEN id END);
